### ISSUE TITLE
Confusion with Test Requirements

### ISSUE THREAD

**Issue by alainalisca** [learn-co-curriculum/phase-1-javascript-variables-lab#16]
### Canvas Link

https://learning.flatironschool.com/courses/4978/assignments/167596?module_item_id=362122

### Concern

The test descriptions were a bit confusing at first to me because it stated that it we should be setting "X" variable equal to "xx" string. Initially, I was trying to use the === operator because in the notes indicated that is the proper way to set one thing equal to another.

**Comment by AlveeM** [comment]
Thanks for bringing up the issue @alainalisca!

Could you tell us which specific test cases were confusing? 

And here's the different between the `=` and `===` operators:

The `=` is the assignment operator. It is used when you want to assign a value to a constant or a variable. For example, the statement `let date = 25` can be read as "declare a variable called date and assign the value 25 to it.

The `===` is the strict equality check operator. It is used when you want to test whether two values are equal or not. For example, `5 === 10` can be read as "is 5 equivalent to 10?". If the values are equal it will evaluate to `true`, otherwise, it will evaluate to `false`.

**Comment by AlveeM** [comment]
Hi alainalisca, I'm closing this issue for now. If you are still having any problems feel free to reopen this issue or submit a new one.
